#!/bin/bash

# Codici ANSI per i colori di foreground
FG_BLACK="\033[30m"
FG_RED="\033[31m"
FG_GREEN="\033[32m"
FG_YELLOW="\033[33m"
FG_BLUE="\033[34m"
FG_MAGENTA="\033[35m"
FG_CYAN="\033[36m"
FG_WHITE="\033[37m"
FG_BRIGHT_BLACK="\033[90m"
FG_BRIGHT_RED="\033[91m"
FG_BRIGHT_GREEN="\033[92m"
FG_BRIGHT_YELLOW="\033[93m"
FG_BRIGHT_BLUE="\033[94m"
FG_BRIGHT_MAGENTA="\033[95m"
FG_BRIGHT_CYAN="\033[96m"
FG_BRIGHT_WHITE="\033[97m"

# Codici ANSI per i colori di background
BG_BLACK="\033[40m"
BG_RED="\033[41m"
BG_GREEN="\033[42m"
BG_YELLOW="\033[43m"
BG_BLUE="\033[44m"
BG_MAGENTA="\033[45m"
BG_CYAN="\033[46m"
BG_WHITE="\033[47m"
BG_BRIGHT_BLACK="\033[100m"
BG_BRIGHT_RED="\033[101m"
BG_BRIGHT_GREEN="\033[102m"
BG_BRIGHT_YELLOW="\033[103m"
BG_BRIGHT_BLUE="\033[104m"
BG_BRIGHT_MAGENTA="\033[105m"
BG_BRIGHT_CYAN="\033[106m"
BG_BRIGHT_WHITE="\033[107m"

# Codici ANSI per gli effetti
EFFECT_BOLD="\033[1m"
EFFECT_DIM="\033[2m"
EFFECT_UNDERLINE="\033[4m"
EFFECT_BLINK="\033[5m"
EFFECT_REVERSED="\033[7m"
EFFECT_HIDDEN="\033[8m"

# Codice ANSI per resettare
RESET="\033[0m"

# Esempio di utilizzo per tutti i codici
echo -e "${FG_BLACK}Testo nero${RESET}"
echo -e "${FG_RED}Testo rosso${RESET}"
echo -e "${FG_GREEN}Testo verde${RESET}"
echo -e "${FG_YELLOW}Testo giallo${RESET}"
echo -e "${FG_BLUE}Testo blu${RESET}"
echo -e "${FG_MAGENTA}Testo magenta${RESET}"
echo -e "${FG_CYAN}Testo ciano${RESET}"
echo -e "${FG_WHITE}Testo bianco${RESET}"
echo -e "${FG_BRIGHT_BLACK}Testo nero brillante${RESET}"
echo -e "${FG_BRIGHT_RED}Testo rosso brillante${RESET}"
echo -e "${FG_BRIGHT_GREEN}Testo verde brillante${RESET}"
echo -e "${FG_BRIGHT_YELLOW}Testo giallo brillante${RESET}"
echo -e "${FG_BRIGHT_BLUE}Testo blu brillante${RESET}"
echo -e "${FG_BRIGHT_MAGENTA}Testo magenta brillante${RESET}"
echo -e "${FG_BRIGHT_CYAN}Testo ciano brillante${RESET}"
echo -e "${FG_BRIGHT_WHITE}Testo bianco brillante${RESET}"

echo -e "${BG_BLACK}Sfondo nero${RESET}"
echo -e "${BG_RED}Sfondo rosso${RESET}"
echo -e "${BG_GREEN}Sfondo verde${RESET}"
echo -e "${BG_YELLOW}Sfondo giallo${RESET}"
echo -e "${BG_BLUE}Sfondo blu${RESET}"
echo -e "${BG_MAGENTA}Sfondo magenta${RESET}"
echo -e "${BG_CYAN}Sfondo ciano${RESET}"
echo -e "${BG_WHITE}Sfondo bianco${RESET}"
echo -e "${BG_BRIGHT_BLACK}Sfondo nero brillante${RESET}"
echo -e "${BG_BRIGHT_RED}Sfondo rosso brillante${RESET}"
echo -e "${BG_BRIGHT_GREEN}Sfondo verde brillante${RESET}"
echo -e "${BG_BRIGHT_YELLOW}Sfondo giallo brillante${RESET}"
echo -e "${BG_BRIGHT_BLUE}Sfondo blu brillante${RESET}"
echo -e "${BG_BRIGHT_MAGENTA}Sfondo magenta brillante${RESET}"
echo -e "${BG_BRIGHT_CYAN}Sfondo ciano brillante${RESET}"
echo -e "${BG_BRIGHT_WHITE}Sfondo bianco brillante${RESET}"

echo -e "${EFFECT_BOLD}Testo in grassetto${RESET}"
echo -e "${EFFECT_DIM}Testo attenuato${RESET}"
echo -e "${EFFECT_UNDERLINE}Testo sottolineato${RESET}"
echo -e "${EFFECT_BLINK}Testo lampeggiante${RESET}"
echo -e "${EFFECT_REVERSED}Testo invertito${RESET}"
echo -e "${EFFECT_HIDDEN}Testo nascosto${RESET}"

# Combinazioni di colori ed effetti
echo -e "${EFFECT_BOLD}${FG_BRIGHT_BLUE}${BG_BRIGHT_YELLOW}Testo blu brillante in grassetto su sfondo giallo brillante${RESET}"
echo -e "${EFFECT_UNDERLINE}${FG_BRIGHT_MAGENTA}${BG_BRIGHT_CYAN}Testo magenta brillante sottolineato su sfondo ciano brillante${RESET}"
echo -e "${EFFECT_REVERSED}${FG_BRIGHT_WHITE}${BG_BRIGHT_RED}Testo bianco brillante invertito su sfondo rosso brillante${RESET}"